name: ph
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - blas=1.0=mkl
  - ca-certificates=2019.5.15=0
  - certifi=2019.6.16=py37_1
  - cffi=1.12.3=py37h2e261b9_0
  - cudatoolkit=10.0.130=0
  - freetype=2.9.1=h8a8886c_1
  - intel-openmp=2019.4=243
  - joblib=0.13.2=py37_0
  - jpeg=9b=h024ee3a_2
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libpng=1.6.37=hbc83047_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.0.10=h2733197_2
  - mkl=2019.4=243
  - mkl-service=2.0.2=py37h7b6447c_0
  - mkl_fft=1.0.12=py37ha843d7b_0
  - mkl_random=1.0.2=py37hd81dba3_0
  - ncurses=6.1=he6710b0_1
  - ninja=1.9.0=py37hfd86e86_0
  - numpy=1.16.4=py37h7e9f1db_0
  - numpy-base=1.16.4=py37hde5b4d6_0
  - olefile=0.46=py37_0
  - openssl=1.1.1c=h7b6447c_1
  - pandas=0.25.0=py37he6710b0_0
  - pillow=6.1.0=py37h34e0f95_0
  - pip=19.1.1=py37_0
  - pycparser=2.19=py37_0
  - python=3.7.3=h0371630_0
  - python-dateutil=2.8.0=py37_0
  - pytorch=1.2.0=py3.7_cuda10.0.130_cudnn7.6.2_0
  - pytz=2019.1=py_0
  - readline=7.0=h7b6447c_5
  - scikit-learn=0.21.2=py37hd81dba3_0
  - scipy=1.3.0=py37h7c811a0_0
  - setuptools=41.0.1=py37_0
  - six=1.12.0=py37_0
  - sqlite=3.29.0=h7b6447c_0
  - tk=8.6.8=hbc83047_0
  - torchvision=0.4.0=py37_cu100
  - wheel=0.33.4=py37_0
  - xz=5.2.4=h14c3975_4
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.3.7=h0b5b093_0
  - pip:
      - argh==0.26.2
      - chardet==3.0.4
      - click==7.0
      - cloudpickle==1.2.1
      - docker-pycreds==0.4.0
      - future==0.17.1
      - gitdb2==2.0.5
      - gitpython==2.1.13
      - gql==0.1.0
      - graphql-core==2.2.1
      - gym==0.14.0
      - idna==2.8
      - nvidia-ml-py3==7.352.0
      - pathtools==0.1.2
      - promise==2.2.1
      - psutil==5.6.3
      - pyglet==1.3.2
      - pyyaml==5.1.2
      - requests==2.22.0
      - rx==1.6.1
      - sentry-sdk==0.10.2
      - shortuuid==0.5.0
      - smmap2==2.0.5
      - subprocess32==3.5.4
      - tqdm==4.33.0
      - urllib3==1.25.3
      - wandb==0.8.7
      - watchdog==0.9.0
prefix: /data/anaconda/envs/ph

